name: Veil CD (Development)

on:
  push:
    tags: 
      - "v*-dev"
      - "v*-internal"

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.vars.outputs.version_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract Variables
        id: vars
        uses: ./.github/actions/extract-vars

  build:
    needs: vars
    uses: ./.github/workflows/_build_flutter.yml
    with:
      flavor: dev
      target: lib/main_dev.dart
      build_type: apk
      version_name: ${{ needs.vars.outputs.version_name }}
      build_number: ${{ github.run_number }}
      artifact_name: dev-release-apk
      artifact_path: build/app/outputs/flutter-apk/app-dev-release.apk
    secrets:
      keystore_base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      keystore_password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
      key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}

